### PR TITLE
added small comments to main.cpp

### PR DESCRIPTION
**Pull request by crystalmapoy**

### CODE REVIEW

**Comment by ellenAvrumova** [comment]
Can you also add some comments in tests.cpp?

**Comment by crystalmapoy** [comment]
There is no file named tests.cpp, do you mean badCode.cpp?

**Comment by ellenAvrumova** [comment]
I'm sorry, can you please add comments in unindent.cpp?

**Comment by ellenAvrumova** [comment]
Thank you!

**Pull request merged**
